import { CalendarDays, Download, TrendingDown, TrendingUp, Wallet } from 'lucide-react';
import { useEffect, useState } from 'react';
import api from '../services/api';
import { formatCurrency } from '../utils/formatters';
import Toast from '../components/Toast';

export default function SummaryPage() {
  const now = new Date(); const [month, setMonth] = useState(now.getMonth() + 1); const [year, setYear] = useState(now.getFullYear()); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [toast, setToast] = useState(null);
  useEffect(() => { setLoading(true); api.get(`/resumo/${year}/${month}`).then(({ data: response }) => setData(response)).catch((error) => setToast({ type: 'error', message: error.userMessage || 'Não foi possível carregar o resumo.' })).finally(() => setLoading(false)); }, [year, month]);
  const expenseCategories = Object.entries(data?.despesasPorCategoria || data?.totalPorCategoria || {});
  const incomeCategories = Object.entries(data?.receitasPorCategoria || {});
  return <div className="page-stack"><Toast toast={toast} onClose={() => setToast(null)} /><div className="page-heading compact"><div><p className="eyebrow">análise financeira</p><h1>Resumo</h1><p className="heading-subtitle">Entenda para onde seu dinheiro está indo.</p></div><button className="secondary-button" onClick={() => window.print()}><Download size={16} /> Exportar</button></div><div className="summary-toolbar"><CalendarDays size={18} /><select value={month} onChange={(event) => setMonth(Number(event.target.value))}>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{new Date(2020, index, 1).toLocaleDateString('pt-BR', { month: 'long' })}</option>)}</select><select value={year} onChange={(event) => setYear(Number(event.target.value))}><option>{year - 1}</option><option>{year}</option><option>{year + 1}</option></select></div>{loading ? <div className="metric-grid"><div className="skeleton summary-skeleton" /><div className="skeleton summary-skeleton" /><div className="skeleton summary-skeleton" /></div> : <><div className="metric-grid"><SummaryMetric title="Receitas" value={data?.totalReceitas} icon={TrendingUp} tone="positive" /><SummaryMetric title="Despesas" value={data?.totalDespesas} icon={TrendingDown} tone="negative" /><SummaryMetric title="Saldo" value={data?.saldo} icon={Wallet} tone={Number(data?.saldo) >= 0 ? 'positive' : 'negative'} /></div><div className="summary-columns"><CategoryPanel title="Despesas por categoria" entries={expenseCategories} tone="negative" /><CategoryPanel title="Receitas por categoria" entries={incomeCategories} tone="positive" /></div></>}</div>;
}
function SummaryMetric({ title, value, icon: Icon, tone }) { return <article className={`metric-card metric-${tone}`}><div className="metric-top"><span>{title}</span><span className="metric-icon"><Icon size={18} /></span></div><strong>{formatCurrency(value)}</strong><span className="metric-caption">período selecionado</span></article>; }
function CategoryPanel({ title, entries, tone }) { return <section className="surface category-panel"><h2>{title}</h2>{entries.length ? <div className="category-list">{entries.map(([name, value]) => <div className="category-line" key={name}><div><span className={`category-dot ${tone}`} /><span>{name.replace('DESPESA:', '')}</span></div><strong>{formatCurrency(value)}</strong><div className="category-progress"><span style={{ width: `${Math.min(Number(value) / Math.max(...entries.map(([, itemValue]) => Number(itemValue))) * 100, 100)}%` }} /></div></div>)}</div> : <p className="muted-copy">Nenhum lançamento no período.</p>}</section>; }
